/** @type {import('tailwindcss').Config} */
module.exports = {
  // Specify paths to all of your component files so Tailwind can scan them
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // This maps the font family name 'unifraktur' to the CSS variable
      // '--font-unifraktur' generated by the Next.js Google Font loader.
      fontFamily: {
        'unifraktur': ['var(--font-unifraktur)', 'serif'],
      },
    },
  },
  plugins: [],
}